# Project 3. CLD Aggregation Tool

Last update: 05/16/2024

Title: Streamlining the Aggregation of Causal Loop Diagrams: A Thematic Labeling and Adjacency Matrix Approach

Overview: 
Spaghetti Causal Loop Diagrams (CLDs) present a significant challenge for modelers in effectively communicating complex system dynamics to stakeholders. Traditionally, modelers manually synthesize multiple CLDs to create an aggregated diagram that provides a higher-level understanding of the system. This paper introduces a streamlined procedure for aggregating CLDs using general categorical labels. The methodology involves translating qualitative mental models into adjacency matrices that capture both links and polarity signs, manually coding and substituting variable names with thematic labels, aggregating these matrices to identify significant feedback loops, and validating the approach by comparing it with the manual synthesis performed by an expert system dynamicist. Our results demonstrate that this tool is highly useful for group model-building experts, particularly when dealing with a large number of mental maps. The proposed method enhances the clarity and efficiency of synthesizing complex CLDs, thereby improving the overall communication of system dynamics.

In [1]:
import numpy as np
import os 
import pickle
import pandas as pd
import sys

# Add the src directory to the sys.path
sys.path.append(os.path.abspath(os.path.join('..', 'src')))

# Import the function from data_io.py
from data_io import read_json
# from parse_cld import get_dataframe, get_adjacency_matrix, get_polarity_matrix
import parse_cld

In [2]:
# Set the new directory
new_dir = "/Users/gl665/PycharmProjects/Phrame_MentalMaps"
# Change the current working directory
os.chdir(new_dir)

print(os.getcwd())

/Users/gl665/PycharmProjects/Phrame_MentalMaps

In [3]:
# Read all the json files in 
my_data_RC = {}
folder_path = 'Output/SYNCH/JSON_file/RC/'

my_data_RC = read_json(folder_path, my_data_RC)

Output/SYNCH/JSON_file/RC/FM 51220Clean.json
load: FM 51220Clean.json
Output/SYNCH/JSON_file/RC/Passages Clean.json
load: Passages Clean.json
Output/SYNCH/JSON_file/RC/full circle GBM 5 24 21clean.json
load: full circle GBM 5 24 21clean.json
Output/SYNCH/JSON_file/RC/C 7 6 20 clean model.json
load: C 7 6 20 clean model.json
Output/SYNCH/JSON_file/RC/tracy clean model.json
load: tracy clean model.json
Output/SYNCH/JSON_file/RC/Wavi combined clean.json
load: Wavi combined clean.json
Output/SYNCH/JSON_file/RC/drug justice model clean.json
load: drug justice model clean.json
Output/SYNCH/JSON_file/RC/7 13 20 clean model.json
load: 7 13 20 clean model.json
Output/SYNCH/JSON_file/RC/DSS23.json
load: DSS23.json
Output/SYNCH/JSON_file/RC/E clean model 572020.json
load: E clean model 572020.json
Output/SYNCH/JSON_file/RC/nat model clean2.json
load: nat model clean2.json
Output/SYNCH/JSON_file/RC/j model 7 13 20 clean model3.json
load: j model 7 13 20 clean model3.json
Output/SYNCH/JSON_file/RC/FC Prov Clean.json
load: FC Prov Clean.json
Output/SYNCH/JSON_file/RC/full circle clean.json
load: full circle clean.json
Output/SYNCH/JSON_file/RC/reentry clean model.json
load: reentry clean model.json
Output/SYNCH/JSON_file/RC/1 6 21 Legal clean.json
load: 1 6 21 Legal clean.json
Output/SYNCH/JSON_file/RC/DV justice model clean.json
load: DV justice model clean.json
Output/SYNCH/JSON_file/RC/SOC clean.json
load: SOC clean.json
Output/SYNCH/JSON_file/RC/RC 4 28 2021 Clean.json
load: RC 4 28 2021 Clean.json

In [4]:
file_rename = pd.read_excel('Output/SYNCH/file_rename/RC_file_rename.xlsx', index_col=0)

file_rename.head(3)

                            Filename Model Name
0                 FM 51220Clean.json         FM
1                Passages Clean.json         PA
2  full circle GBM 5 24 21clean.json    FullGMB

In [5]:
adj_matrix_dic = dict(zip(file_rename['Model Name'], my_data_RC.values()))
adj_matrix_dic['FM']

df_fm = parse_cld.get_dataframe(adj_matrix_dic['FM'])
df_fm
# adj_mx = get_adjacency_matrix(df_fm)
# pol_mx = get_polarity_matrix(df_fm)

# print(adj_mx)
# print(pol_mx)

    from   to  polarity_type  links
0      1    2              3      1
1      1    3              3      1
2      1   64              3      1
3      1  125              3      1
4      1  243              3      1
..   ...  ...            ...    ...
300   97  413              3      1
301   99   97              3      1
302   99   13              3      1
303   99   72              3      1
304   99  122              3      1

[305 rows x 4 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 305 entries, 0 to 304
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   from           305 non-null    object
 1   to             305 non-null    object
 2   polarity_type  305 non-null    int64
 3   links          305 non-null    int64
dtypes: int64(2), object(2)
memory usage: 9.7+ KB
None

    from   to  polarity_type  links
0      1    2              3      1
1      1    3              3      1
2      1   64              3      1
3      1  125              3      1
4      1  243              3      1
..   ...  ...            ...    ...
300   97  413              3      1
301   99   97              3      1
302   99   13              3      1
303   99   72              3      1
304   99  122              3      1

[305 rows x 4 columns]

In [9]:
adj_mx = parse_cld.get_adjacency_matrix(df_fm)
print(adj_mx)
pol_mx = parse_cld.get_polarity_matrix(df_fm)
print(pol_mx)

to    1  106  108  11  111  116  119  12  122  125  ...  72  74  75  82  84  \
from                                                ...
1     0    0    0   0    0    0    0   0    0    1  ...   0   0   0   0   0
106   1    0    0   0    0    0    0   0    0    0  ...   0   0   0   0   0
108   0    0    0   0    0    0    0   0    0    0  ...   0   0   0   0   0
11    1    0    0   0    0    0    0   0    0    0  ...   0   0   0   0   0
111   1    0    0   0    0    0    0   0    0    0  ...   0   0   0   0   0
...  ..  ...  ...  ..  ...  ...  ...  ..  ...  ...  ...  ..  ..  ..  ..  ..
88    0    0    0   0    0    0    0   0    0    0  ...   1   0   0   0   0
92    0    0    0   0    0    0    0   0    0    0  ...   0   0   0   0   0
95    0    0    0   0    0    0    0   0    0    0  ...   0   0   0   0   0
97    0    0    0   0    0    0    0   0    1    0  ...   1   0   0   0   0
99    0    0    0   0    0    0    0   0    1    0  ...   1   0   0   0   0

to    88  92  95  97  99
from
1      0   0   0   0   0
106    0   0   0   0   0
108    0   0   0   0   0
11     0   0   0   0   0
111    0   0   0   0   0
...   ..  ..  ..  ..  ..
88     0   1   0   0   0
92     1   0   0   0   0
95     0   0   0   1   0
97     0   0   0   0   1
99     0   0   0   1   0

[182 rows x 182 columns]
to    1  106  108  11  111  116  119  12  122  125  ...  72  74  75  82  84  \
from                                                ...
1     0    0    0   0    0    0    0   0    0    3  ...   0   0   0   0   0
106   3    0    0   0    0    0    0   0    0    0  ...   0   0   0   0   0
108   0    0    0   0    0    0    0   0    0    0  ...   0   0   0   0   0
11    3    0    0   0    0    0    0   0    0    0  ...   0   0   0   0   0
111   3    0    0   0    0    0    0   0    0    0  ...   0   0   0   0   0
...  ..  ...  ...  ..  ...  ...  ...  ..  ...  ...  ...  ..  ..  ..  ..  ..
88    0    0    0   0    0    0    0   0    0    0  ...   3   0   0   0   0
92    0    0    0   0    0    0    0   0    0    0  ...   0   0   0   0   0
95    0    0    0   0    0    0    0   0    0    0  ...   0   0   0   0   0
97    0    0    0   0    0    0    0   0    3    0  ...   3   0   0   0   0
99    0    0    0   0    0    0    0   0    3    0  ...   3   0   0   0   0

to    88  92  95  97  99
from
1      0   0   0   0   0
106    0   0   0   0   0
108    0   0   0   0   0
11     0   0   0   0   0
111    0   0   0   0   0
...   ..  ..  ..  ..  ..
88     0   1   0   0   0
92     1   0   0   0   0
95     0   0   0   3   0
97     0   0   0   0   3
99     0   0   0   3   0

[182 rows x 182 columns]

In [6]:
df_rc_themes = pd.read_excel('Dataset/SYNCH/aggregate_theme/RC_Updated_Themes.xlsx', sheet_name= "edited")

In [7]:
model_name = list(df_rc_themes['Model'])
# seperate by ";" and "," 
# model_name = [x.split(";") for x in model_name]
# model_name
# get unique model names 
unique_model_name = list(set(model_name)) 
print(unique_model_name)

['justice - drugs', 'Justice-IPV', 'reentry model', 'FC (provider)', 'J Model', 'E model; FM model', 'WAVI;', 'E Model', 'WAVI;full circle;DSSjustice-drugs; e model;fm model;j model; reentry model', 'Passages', 'FC(Patients)', 'FC; Justice-IPV', 'FC (Provider)', 'Full Circle (Patient)', 'DSS/Full Circle Provider;E model', 'C model', nan, 'Full Circle (Patient Combined); E model; j model', 'Justice-Drugs ; FC (Provider)', 'FC;DSS;justice IPV', 'Nat Model; reentry model; FM model; E model', 'Most models', 'Full Circle (Patient); FC Provider', 'Justice-drugs; Reentry', 'reentry', 'WAVI; FC (Patients);DSS;E model; j model', 'WAVI ; FC', 'fc (provider); e model', 'Nat Model; c model', 'justice-drugs;justice-IPV', 'Justice-drugs; FM model; J model', 'Justice-Drugs', 'justice - ipv', 'Justice  IPV', 'FM model', 'justice-IPV', 'Justice-IPV; FC (Provider)', 'wavi', 'WAVI', 'FC (Patient', 'J model', 'passages;wavi;full circle (patient)', 'FC;justice IPV', 'justice-ipv', 'dss', 'FC (Provider); e model', 'Full Circle (Provider)', 'WAVI (combined)', 'actually receiving/engaging with resources to help address needs', 'DSS; justice-IPV', 'FC( Patient)', 'FC', 'FM Model;  E model', 'FC (patients)', 'Passages ', 'DSS; FC (Patient); Justice-drugs', 'j model', 'DSS; justice-drugs', 'FC Patients', 'fc (provider)', 'justice-IPV; FC (Provider)', 'Full circle (Patient)', 'J model; reentry model', 'E model', 'justice-IPV; FM model', 'nat model', 'DSS; nat model', 'E model?', 'FC; justice-IPV', 'passages', 'justice-ipv; e model', 'Wavi; full circle (patient combined); DSS; Justice-IPV; full circle (provider); FM model; J model; C model', 'DSS;E model', 'DSS/E model', 'FM Model', '(many)', 'Justice IPV', 'WAVI;Passages;', 'FC; FM model', 'FC (Patient)', 'justice-IPV / e model', 'Nat model', 'DSS', 'all', 'e model', 'FC (provider); E model', 'justice-drugs', 'Justice-drugs', 'WAVI; Justice IPV; Reentry']

In [8]:
model_name

[nan,
 'FC (Provider)',
 'FC (Provider)',
 'DSS',
 'J model',
 'justice-drugs',
 'Most models',
 'DSS; justice-drugs',
 'reentry',
 'FM Model',
 'Passages',
 'Full circle (Patient)',
 'nat model',
 'justice-drugs',
 'reentry',
 'justice - drugs',
 'wavi',
 'passages;wavi;full circle (patient)',
 'FC (Provider)',
 'WAVI (combined)',
 'E model',
 'justice-drugs',
 'FM model',
 'reentry',
 'reentry',
 'justice-drugs',
 'reentry',
 'WAVI',
 'E model',
 'Nat model',
 'j model',
 'j model',
 'j model',
 'passages',
 'Passages',
 'Full Circle (Patient)',
 'FM model',
 'FC (Provider)',
 'Justice-Drugs',
 'E model',
 'justice-drugs',
 'WAVI',
 'Justice-Drugs',
 'reentry',
 'Justice-drugs',
 nan,
 'reentry',
 'DSS',
 'reentry model',
 'reentry model',
 'reentry model',
 'reentry model',
 'reentry model',
 'Justice-Drugs',
 'j model',
 'reentry',
 'DSS',
 'reentry',
 nan,
 'passages',
 'FM model',
 'WAVI; Justice IPV; Reentry',
 'Justice-drugs; FM model; J model',
 'Justice-drugs; Reentry',
 'FM model',
 'Justice-drugs',
 'Full Circle (Patient); FC Provider',
 'justice-IPV',
 'FM model',
 'Full Circle (Patient Combined); E model; j model',
 'WAVI;Passages;',
 'justice-IPV',
 'DSS',
 'nat model',
 'Full Circle (Provider)',
 'Full Circle (Provider)',
 'dss',
 'Justice-drugs',
 'j model',
 'dss',
 'dss',
 'FM model',
 'FC',
 'FC',
 'justice-drugs',
 'justice-drugs',
 'justice-drugs',
 'DSS; justice-drugs',
 'FC; FM model',
 'j model',
 'FC; justice-IPV',
 'WAVI',
 'WAVI ; FC',
 'DSS',
 'DSS',
 'Justice-drugs',
 'FC',
 'justice-IPV',
 'DSS',
 nan,
 'justice-IPV',
 'justice-IPV / e model',
 'E model',
 'E model',
 'E model',
 'Passages ',
 'j model',
 'j model',
 'j model',
 'j model',
 'WAVI (combined)',
 'WAVI (combined)',
 'WAVI (combined)',
 'passages',
 'WAVI',
 'reentry',
 'reentry',
 nan,
 nan,
 nan,
 'reentry',
 'reentry',
 'Justice-Drugs',
 'reentry',
 'reentry',
 'reentry',
 'DSS',
 'passages',
 'WAVI',
 nan,
 'WAVI (combined)',
 'Passages',
 'WAVI',
 'DSS',
 'WAVI;full circle;DSSjustice-drugs; e model;fm model;j model; reentry model',
 'DSS',
 'FC (Provider)',
 'FC (Provider)',
 'J model; reentry model',
 'Nat Model; reentry model; FM model; E model',
 'justice-drugs',
 'FM Model',
 'FM Model',
 nan,
 'DSS',
 'Justice-Drugs',
 'justice-IPV; FC (Provider)',
 'FC (Provider); e model',
 'FC (Provider); e model',
 nan,
 'reentry model',
 'reentry model',
 'reentry model',
 'e model',
 'FM Model',
 'reentry',
 nan,
 'j model',
 'Full Circle (Provider)',
 'reentry',
 nan,
 'FC; Justice-IPV',
 'justice-IPV',
 'Full Circle (Provider)',
 'FC (provider); E model',
 'FC (provider); E model',
 'FC (provider); E model',
 'Justice-drugs',
 'reentry',
 'reentry',
 'reentry',
 'DSS',
 'E model?',
 'FC (Patient)',
 'reentry',
 'reentry',
 'DSS',
 nan,
 nan,
 'Passages ',
 'fc (provider)',
 nan,
 'fc (provider); e model',
 nan,
 nan,
 nan,
 'WAVI',
 'WAVI',
 'DSS',
 'Justice-Drugs',
 'DSS',
 'Justice-drugs',
 'FC (Patient)',
 'E model?',
 'justice-IPV',
 'reentry model',
 'j model',
 'DSS',
 'reentry model',
 'j model',
 nan,
 'WAVI',
 'FC (Provider)',
 'Justice-Drugs',
 'FC (Provider)',
 'FM Model',
 'justice-ipv; e model',
 'e model',
 'FM model',
 'DSS',
 'DSS',
 'DSS',
 'FC (provider)',
 'Justice-Drugs',
 'Justice-IPV; FC (Provider)',
 'j model',
 'FC (provider)',
 'FM Model',
 'FC (provider)',
 'FC Patients',
 'j model',
 'DSS',
 'DSS',
 'DSS',
 'Justice-Drugs',
 nan,
 'reentry',
 'reentry',
 'reentry',
 'Justice-Drugs',
 'FC (Patient',
 'DSS',
 'DSS',
 'DSS',
 'FC (Patient)',
 'justice-IPV',
 'justice-IPV',
 'Justice-Drugs',
 'j model',
 'j model',
 'FC (Patient)',
 'justice-drugs',
 'FC (provider)',
 'passages',
 'FC (provider)',
 nan,
 'wavi',
 'Full circle (Patient)',
 'justice - drugs',
 'reentry',
 'FC (Provider)',
 'FM Model',
 'FM Model',
 'FM Model',
 nan,
 nan,
 'all',
 'FC',
 'justice-ipv',
 'justice-ipv',
 'justice-ipv',
 'FC; justice-IPV',
 'justice-IPV',
 'WAVI',
 'justice-IPV / e model',
 'DSS',
 'DSS',
 'DSS',
 'DSS',
 'justice-ipv',
 'justice-ipv',
 'justice-ipv',
 'Justice-IPV',
 'FC; Justice-IPV',
 'E model',
 'e model',
 'FC',
 'justice-IPV',
 'WAVI',
 'justice-IPV / e model',
 'Wavi; full circle (patient combined); DSS; Justice-IPV; full circle (provider); FM model; J model; C model',
 'FM model',
 'WAVI',
 'FM model',
 'J model',
 'justice-IPV; FM model',
 'justice-IPV',
 'reentry model',
 'FM model',
 'FM model',
 'FM model',
 'j model',
 'j model',
 'justice-IPV',
 'J model',
 'J model',
 'J model',
 'Nat Model; c model',
 'j model',
 'nat model',
 'FM model',
 'J Model',
 'FM model',
 'FC',
 'DSS',
 'justice-IPV',
 'justice-IPV; FM model',
 'justice-IPV',
 'WAVI',
 'WAVI',
 'FC',
 'FC',
 'justice-ipv',
 'j model',
 'WAVI',
 'j model',
 'j model',
 'reentry model',
 'FM model',
 'J model',
 'j model',
 'FM model',
 'FM model',
 nan,
 'j model',
 'DSS',
 'DSS',
 'DSS',
 'Full Circle (Provider)',
 'WAVI (combined)',
 'WAVI',
 'dss',
 'Full Circle (Provider)',
 'WAVI (combined)',
 'WAVI (combined)',
 nan,
 'FC (provider)',
 'Justice-Drugs ; FC (Provider)',
 'FC (provider)',
 'fc (provider)',
 'FC (Provider)',
 'j model',
 'FC (provider)',
 'Justice-Drugs',
 'justice-drugs',
 'FC (provider)',
 'Justice-Drugs',
 'FC (provider)',
 nan,
 'j model',
 'E model',
 'E model',
 'justice-ipv',
 'E model',
 'j model',
 'E model',
 'E model',
 'j model',
 'j model',
 'E model',
 'E model',
 'E model',
 'E model',
 'E model',
 'E model',
 'Justice-drugs',
 'fc (provider); e model',
 nan,
 nan,
 nan,
 nan,
 nan,
 'DSS; FC (Patient); Justice-drugs',
 'FC (Provider)',
 'DSS',
 'reentry',
 'DSS',
 'reentry',
 nan,
 nan,
 'reentry',
 'reentry',
 'reentry',
 'DSS',
 'DSS',
 'DSS',
 'reentry',
 nan,
 'DSS',
 'DSS',
 'FC (Provider)',
 'e model',
 'FC (Provider)',
 'e model',
 'e model',
 'e model',
 'e model',
 'WAVI',
 'FC (Provider)',
 'Justice-Drugs',
 'FC (Provider)',
 'DSS',
 'DSS',
 'Justice-Drugs',
 nan,
 nan,
 '(many)',
 'C model',
 'reentry model',
 'DSS',
 'DSS',
 'reentry model',
 'DSS',
 'DSS',
 'dss',
 'Passages',
 '(many)',
 'reentry model',
 'WAVI; FC (Patients);DSS;E model; j model',
 'DSS',
 'DSS',
 'DSS',
 'DSS',
 'FC (patients)',
 'DSS',
 'DSS',
 'dss',
 'DSS/Full Circle Provider;E model',
 'DSS',
 'DSS',
 'DSS',
 'DSS',
 'DSS',
 'DSS',
 'DSS',
 'j model',
 'DSS',
 'FC Patients',
 'DSS',
 'DSS',
 'DSS',
 'DSS',
 'DSS',
 'DSS',
 'DSS',
 'DSS',
 'DSS',
 'DSS',
 'DSS',
 'DSS',
 'DSS',
 'DSS',
 'DSS',
 'DSS',
 'DSS',
 'E Model',
 'E model',
 'E model',
 'reentry model',
 'E model',
 'DSS',
 'dss',
 '(many)',
 'FC Patients',
 'DSS',
 'DSS',
 'FC (patients)',
 'DSS',
 'DSS',
 'DSS',
 'DSS',
 'DSS',
 'DSS',
 'DSS',
 'actually receiving/engaging with resources to help address needs',
 nan,
 'DSS',
 'FC (patients)',
 'DSS',
 'DSS',
 'DSS',
 'DSS',
 'DSS',
 'DSS',
 'DSS',
 'WAVI;',
 'DSS',
 'DSS',
 'DSS',
 'DSS',
 'DSS',
 'DSS',
 'FC (patients)',
 'DSS/E model',
 'DSS',
 'DSS',
 'DSS;E model',
 'E model',
 'E model',
 nan,
 'DSS/E model',
 'DSS',
 'DSS',
 'FC(Patients)',
 'DSS',
 'E model',
 'DSS',
 'DSS',
 'Nat model',
 'DSS; nat model',
 nan,
 'justice-ipv',
 'justice-ipv',
 'justice-ipv',
 'e model',
 'e model',
 'Justice  IPV',
 'Justice IPV',
 'Justice IPV',
 'e model',
 'e model',
 'e model',
 'justice-ipv',
 'FC',
 'justice-ipv',
 'justice-ipv',
 'DSS; justice-IPV',
 'reentry',
 nan,
 'reentry',
 'reentry',
 'FC( Patient)',
 'FC( Patient)',
 'justice-IPV',
 'FC (Patient)',
 'reentry',
 'reentry',
 'justice-ipv',
 'Justice-IPV',
 'FC( Patient)',
 'FC (Patient)',
 'FC (Patient)',
 'Justice-Drugs',
 'FC',
 'e model',
 'DSS',
 nan,
 nan,
 nan,
 nan,
 nan,
 'justice-ipv',
 'reentry',
 'FC;DSS;justice IPV',
 'justice-ipv',
 'reentry',
 'reentry',
 'DSS',
 'justice-ipv',
 'justice-ipv',
 'justice-ipv',
 'justice-ipv',
 'justice-ipv',
 'justice-ipv',
 'justice-ipv',
 'justice-ipv',
 'FC',
 'FC',
 'justice-IPV',
 nan,
 'DSS',
 'DSS',
 'justice-ipv',
 'FC',
 'FC',
 'justice-drugs;justice-IPV',
 'FC',
 'Justice IPV',
 'Justice IPV',
 'Justice IPV',
 'FC;justice IPV',
 'DSS; FC (Patient); Justice-drugs',
 'DSS',
 'FC (Provider)',
 'justice-IPV',
 'justice-ipv; e model',
 'j model',
 'FM model',
 nan,
 nan,
 nan,
 'E model',
 'justice-ipv',
 'reentry',
 'justice-ipv',
 'Justice-IPV',
 'DSS; FC (Patient); Justice-drugs',
 'j model',
 'FC (Provider)',
 nan,
 'reentry model',
 'reentry model',
 'reentry model',
 'reentry',
 'reentry',
 'reentry',
 'reentry',
 'reentry',
 'reentry model',
 'reentry model',
 'reentry model',
 'Passages ',
 'reentry',
 'justice-IPV',
 'reentry model',
 'reentry model',
 'reentry model',
 'reentry model',
 'justice-IPV',
 'justice-IPV',
 'justice-ipv',
 'reentry',
 'reentry',
 'reentry',
 'reentry',
 'reentry',
 'reentry',
 'reentry',
 'reentry',
 'reentry',
 nan,
 nan,
 'FC (patients)',
 'FM model',
 'E model; FM model',
 'E model; FM model',
 'FM Model',
 'FM Model',
 'FM Model',
 'E model',
 'FM Model',
 'E model',
 'E model',
 'E model; FM model',
 nan,
 'FM model',
 'FM Model',
 'FM Model',
 'FM model',
 'FM model',
 'FM Model',
 'FC (Patient)',
 'FC (Provider)',
 'FC (Provider)',
 'FM Model',
 'FM Model',
 'FM Model',
 'FM Model;  E model',
 'FM Model',
 'justice-ipv',
 'justice-ipv',
 'FC (provider)',
 'e model',
 'e model',
 'e model',
 'e model',
 'e model',
 'e model',
 'e model',
 'e model',
 'FM Model',
 'FM Model',
 'FM Model',
 'FM Model',
 'FM Model',
 'FM Model',
 'FM Model',
 'FM Model',
 'FM Model',
 nan,
 'Full circle (Patient)',
 'Nat model',
 'nat model',
 'nat model',
 'Full circle (Patient)',
 'WAVI',
 'justice - ipv',
 'E model',
 'j model',
 'justice - ipv',
 'justice - ipv',
 'Full circle (Patient)',
 'FM Model',
 'reentry',
 'nat model',
 'FM Model',
 'FM Model',
 'FM Model',
 nan,
 'FM Model',
 'FM Model',
 'E model',
 'FM Model',
 'Full Circle (Patient)',
 'E model',
 'nat model',
 'E model',
 'E model',
 'nat model',
 'J model',
 'e model',
 'FC (Patient)',
 'nat model',
 'FM Model',
 'FM Model',
 'FM Model',
 'j model',
 'nat model',
 'Nat model',
 'FC (Patient)',
 'FM model',
 'reentry model',
 nan,
 'reentry',
 'j model',
 nan,
 'FM Model',
 nan,
 'FM Model',
 nan,
 nan,
 'FC;justice IPV']