# Project 3. CLD Aggregation Tool

Last update: 05/16/2024

Title: Streamlining the Aggregation of Causal Loop Diagrams: A Thematic Labeling and Adjacency Matrix Approach

Overview: 
Spaghetti Causal Loop Diagrams (CLDs) present a significant challenge for modelers in effectively communicating complex system dynamics to stakeholders. Traditionally, modelers manually synthesize multiple CLDs to create an aggregated diagram that provides a higher-level understanding of the system. This paper introduces a streamlined procedure for aggregating CLDs using general categorical labels. The methodology involves translating qualitative mental models into adjacency matrices that capture both links and polarity signs, manually coding and substituting variable names with thematic labels, aggregating these matrices to identify significant feedback loops, and validating the approach by comparing it with the manual synthesis performed by an expert system dynamicist. Our results demonstrate that this tool is highly useful for group model-building experts, particularly when dealing with a large number of mental maps. The proposed method enhances the clarity and efficiency of synthesizing complex CLDs, thereby improving the overall communication of system dynamics.

In [1]:
import numpy as np
import os 
import pickle
import pandas as pd
import sys

# Add the src directory to the sys.path
sys.path.append(os.path.abspath(os.path.join('..', 'src')))

# Import the function from data_io.py
from data_io import read_json
# from parse_cld import get_dataframe, get_adjacency_matrix, get_polarity_matrix
import parse_cld

In [2]:
# Set the new directory
new_dir = "/Users/gl665/PycharmProjects/Phrame_MentalMaps"
# Change the current working directory
os.chdir(new_dir)

print(os.getcwd())

/Users/gl665/PycharmProjects/Phrame_MentalMaps

In [3]:
# Read all the json files in 
my_data_RC = {}
folder_path = 'Output/SYNCH/JSON_file/RC/'

my_data_RC = read_json(folder_path, my_data_RC)

Output/SYNCH/JSON_file/RC/FM 51220Clean.json
load: FM 51220Clean.json
Output/SYNCH/JSON_file/RC/Passages Clean.json
load: Passages Clean.json
Output/SYNCH/JSON_file/RC/full circle GBM 5 24 21clean.json
load: full circle GBM 5 24 21clean.json
Output/SYNCH/JSON_file/RC/C 7 6 20 clean model.json
load: C 7 6 20 clean model.json
Output/SYNCH/JSON_file/RC/tracy clean model.json
load: tracy clean model.json
Output/SYNCH/JSON_file/RC/Wavi combined clean.json
load: Wavi combined clean.json
Output/SYNCH/JSON_file/RC/drug justice model clean.json
load: drug justice model clean.json
Output/SYNCH/JSON_file/RC/7 13 20 clean model.json
load: 7 13 20 clean model.json
Output/SYNCH/JSON_file/RC/DSS23.json
load: DSS23.json
Output/SYNCH/JSON_file/RC/E clean model 572020.json
load: E clean model 572020.json
Output/SYNCH/JSON_file/RC/nat model clean2.json
load: nat model clean2.json
Output/SYNCH/JSON_file/RC/j model 7 13 20 clean model3.json
load: j model 7 13 20 clean model3.json
Output/SYNCH/JSON_file/RC/FC Prov Clean.json
load: FC Prov Clean.json
Output/SYNCH/JSON_file/RC/full circle clean.json
load: full circle clean.json
Output/SYNCH/JSON_file/RC/reentry clean model.json
load: reentry clean model.json
Output/SYNCH/JSON_file/RC/1 6 21 Legal clean.json
load: 1 6 21 Legal clean.json
Output/SYNCH/JSON_file/RC/DV justice model clean.json
load: DV justice model clean.json
Output/SYNCH/JSON_file/RC/SOC clean.json
load: SOC clean.json
Output/SYNCH/JSON_file/RC/RC 4 28 2021 Clean.json
load: RC 4 28 2021 Clean.json

In [4]:
# file_rename = pd.read_excel('Output/SYNCH/file_rename/RC_file_rename.xlsx', index_col=0)



# file_rename['file_no.'] = [i+1 for i in range(len(file_rename.index))]

# file_rename.head(3)

In [5]:
my_data_RC['Passages Clean.json'][0]

{'1': 'Alcohol Misuse',
 '2': 'Intimate Partner Violence',
 '3': '"Negative Partners (Broken Person)"',
 '4': 'Higher Power',
 '5': '"Passages (Re-Entry Facility)"',
 '6': 'Healing',
 '7': 'Supportive People',
 '8': 'Accountablility',
 '9': 'Coping Skills',
 '10': 'Drugs',
 '11': 'Alcohol exposed pregnancy',
 '12': 'Death',
 '13': 'Family Emotional health',
 '14': 'Dire situtations',
 '15': 'Jail',
 '16': 'Mental Health',
 '32': 'Intimate Partner Violence',
 '52': 'Higher Power',
 '60': 'Structure and Love',
 '61': '"Family and Child Loss (Legal)"',
 '73': 'Drugs',
 '76': 'Alcohol exposed pregnancy',
 '78': 'Intimate Partner Violence',
 '84': 'Alcohol Misuse'}

In [6]:
# adj_matrix_dic = dict(zip(file_rename['Model Name'], my_data_RC.values()))
# adj_matrix_dic['FM']


dict_vars, df = parse_cld.get_dataframe(my_data_RC['Passages Clean.json'])
dict_vars
df

   from  to  polarity_type  links
0     1   2              1      1
1     1  13             -1      1
2     1  14              1      1
3     1  16             -1      1
4     1  15              3      1
..  ...  ..            ...    ...
56    8  16              1      1
57    8   9              1      1
58    8   6              1      1
59    8   4              1      1
60   84   7             -1      1

[61 rows x 4 columns]

In [7]:
adj_mx = parse_cld.get_adjacency_matrix(df)
print(adj_mx)
pol_mx = parse_cld.get_polarity_matrix(df)
print(pol_mx)

to    1  10  11  12  13  14  15  16  2  3  ...  6  60  61  7  73  76  78  8  \
from                                       ...
1     0   1   1   0   1   1   1   1  1  0  ...  0   0   1  0   0   0   0  0
10    1   0   0   0   0   0   0   1  1  0  ...  0   0   0  0   0   0   0  0
11    0   0   0   0   0   0   1   0  0  0  ...  0   0   1  0   0   0   0  0
12    0   0   0   0   0   0   0   0  0  0  ...  0   0   0  0   0   0   0  0
13    0   0   0   0   0   0   0   1  0  0  ...  0   0   0  0   0   0   0  0
14    0   0   0   0   0   0   0   0  0  0  ...  0   0   0  0   0   0   0  0
15    0   0   0   0   0   0   0   0  0  0  ...  0   0   0  0   0   0   0  0
16    1   0   0   0   0   0   0   0  1  0  ...  1   0   0  1   0   0   0  0
2     1   1   0   0   0   1   1   1  0  1  ...  0   0   0  0   0   0   0  0
3     0   0   0   0   0   0   0   0  1  0  ...  0   0   0  0   0   0   0  0
32    0   0   0   1   0   0   0   0  0  0  ...  0   0   1  0   0   0   0  0
4     0   0   0   0   0   0   0   0  0  1  ...  1   0   0  0   0   0   0  0
5     0   0   0   0   0   0   0   0  0  0  ...  0   1   0  1   0   0   0  0
52    1   1   0   0   0   0   0   1  0  0  ...  0   0   0  0   0   0   0  1
6     0   0   0   0   0   0   0   1  0  0  ...  0   0   0  1   0   0   0  0
60    0   0   0   0   0   0   0   0  0  0  ...  1   0   0  0   0   0   0  1
61    0   0   0   0   0   0   0   1  0  0  ...  0   0   0  0   0   0   0  0
7     0   0   0   0   0   0   0   1  0  0  ...  1   0   0  0   0   0   0  1
73    0   0   0   0   0   0   1   0  0  0  ...  0   0   0  0   0   0   0  0
76    0   0   0   0   0   0   0   1  0  0  ...  0   0   0  0   0   0   0  0
78    0   0   0   0   0   0   0   0  0  0  ...  0   0   0  1   0   0   0  0
8     0   0   0   0   0   0   0   1  0  0  ...  1   0   0  0   0   0   0  0
84    0   0   0   0   0   0   0   0  0  0  ...  0   0   0  1   0   0   0  0
9     0   0   0   0   0   0   0   0  0  0  ...  0   0   0  0   0   0   0  0

to    84  9
from
1      0  0
10     0  0
11     0  0
12     0  0
13     0  0
14     0  0
15     0  0
16     0  1
2      0  0
3      0  0
32     0  0
4      0  0
5      0  0
52     0  1
6      0  0
60     0  0
61     0  0
7      0  0
73     0  0
76     0  0
78     0  0
8      0  1
84     0  0
9      0  0

[24 rows x 24 columns]
to    1  10  11  12  13  14  15  16  2  3  ...  6  60  61  7  73  76  78  8  \
from                                       ...
1     0   1   1   0  -1   1   3  -1  1  0  ...  0   0   1  0   0   0   0  0
10    1   0   0   0   0   0   0   3  1  0  ...  0   0   0  0   0   0   0  0
11    0   0   0   0   0   0   1   0  0  0  ...  0   0   1  0   0   0   0  0
12    0   0   0   0   0   0   0   0  0  0  ...  0   0   0  0   0   0   0  0
13    0   0   0   0   0   0   0   1  0  0  ...  0   0   0  0   0   0   0  0
14    0   0   0   0   0   0   0   0  0  0  ...  0   0   0  0   0   0   0  0
15    0   0   0   0   0   0   0   0  0  0  ...  0   0   0  0   0   0   0  0
16   -1   0   0   0   0   0   0   0 -1  0  ...  3   0   0  1   0   0   0  0
2     1   1   0   0   0   3   1  -1  0  1  ...  0   0   0  0   0   0   0  0
3     0   0   0   0   0   0   0   0  1  0  ...  0   0   0  0   0   0   0  0
32    0   0   0   1   0   0   0   0  0  0  ...  0   0   1  0   0   0   0  0
4     0   0   0   0   0   0   0   0  0 -1  ...  1   0   0  0   0   0   0  0
5     0   0   0   0   0   0   0   0  0  0  ...  0   1   0  3   0   0   0  0
52   -1  -1   0   0   0   0   0   1  0  0  ...  0   0   0  0   0   0   0  1
6     0   0   0   0   0   0   0   3  0  0  ...  0   0   0  1   0   0   0  0
60    0   0   0   0   0   0   0   0  0  0  ...  1   0   0  0   0   0   0  1
61    0   0   0   0   0   0   0  -1  0  0  ...  0   0   0  0   0   0   0  0
7     0   0   0   0   0   0   0   1  0  0  ...  1   0   0  0   0   0   0  1
73    0   0   0   0   0   0   1   0  0  0  ...  0   0   0  0   0   0   0  0
76    0   0   0   0   0   0   0  -1  0  0  ...  0   0   0  0   0   0   0  0
78    0   0   0   0   0   0   0   0  0  0  ...  0   0   0 -1   0   0   0  0
8     0   0   0   0   0   0   0   1  0  0  ...  1   0   0  0   0   0   0  0
84    0   0   0   0   0   0   0   0  0  0  ...  0   0   0 -1   0   0   0  0
9     0   0   0   0   0   0   0   0  0  0  ...  0   0   0  0   0   0   0  0

to    84  9
from
1      0  0
10     0  0
11     0  0
12     0  0
13     0  0
14     0  0
15     0  0
16     0  1
2      0  0
3      0  0
32     0  0
4      0  0
5      0  0
52     0  3
6      0  0
60     0  0
61     0  0
7      0  0
73     0  0
76     0  0
78     0  0
8      0  1
84     0  0
9      0  0

[24 rows x 24 columns]

Take "Rapid City Update Themes" Excel Sheet "Clean" column B for Aggregated Variable Name and column E for orignial Variable name

In [8]:
df_rc_themes = pd.read_excel('Dataset/SYNCH/aggregate_theme/RC_Updated_Themes.xlsx', sheet_name= "clean")

# get column 1 and 4
df_aggregate_names = df_rc_themes.iloc[:, [1, 4]]

df_aggregate_names.columns = ['theme', 'variable']
# delete rows if both are column values are nan 
df_aggregate_names = df_aggregate_names.dropna(subset=['theme', 'variable'], how='all')


df_aggregate_names['theme'] = df_aggregate_names['theme'].fillna(method='ffill')

df_aggregate_names['theme']= df_aggregate_names['theme'].str.lower()
df_aggregate_names['variable']= df_aggregate_names['variable'].str.lower()

df_aggregate_names.head(20)

/var/folders/sg/c6q1bz_d6s5fwn637scs4f3c0000gs/T/ipykernel_16184/4123523270.py:11: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_aggregate_names['theme'] = df_aggregate_names['theme'].fillna(method='ffill')

,theme,variable
1,healthy development,child psychological development
2,healthy development,healthy child development
3,healthy development,child behavioral issues
4,healthy development,child physcial violent perpetration
5,healthy development,developmental delay in child
6,mental health,mental health
7,mental health,ment health needs
8,mental health,prison mental health
9,emotional distress,grief
10,emotional distress,death
11,emotional distress,self-worthlessness
12,emotional distress,caring for family stress
13,emotional distress,unresolved individual trauma
14,emotional distress,frustration with lack of finances/effort
15,individual protective coping skills,knowledge of mh needs
16,individual protective coping skills,personal strength
17,individual protective coping skills,coping skills
18,individual protective coping skills,positive coping skills
19,individual protective coping skills,healthy coping skills
20,individual protective coping skills,psychological flourishing life skills

In [14]:
# pd.set_option('display.max_rows', None)
# df_aggregate_names

In [10]:
df_aggregate_names.head()

                 theme                             variable
1  healthy development      child psychological development
2  healthy development            healthy child development
3  healthy development              child behavioral issues
4  healthy development  child physcial violent perpetration
5  healthy development         developmental delay in child

In [11]:
# df_aggregate_names['Variable'][1]
# dict_vars.rename(columns={'Variable': 'Variable Name'}, inplace=True)

In [12]:

# create a pd datframe 
vars_cld = pd.DataFrame.from_dict(dict_vars, orient='index').reset_index()#.columns(['Vensim Var No.', 'Var Name'])
# rename columns 
vars_cld.columns = ['vensim_var_no','var_name']
# turn all the variable names to lowercap 
vars_cld['var_name'] = vars_cld['var_name'].str.lower()
# delete the "" sign 
vars_cld['var_name'] = vars_cld['var_name'].str.replace('"', '')
vars_cld.head(10)

  vensim_var_no                           var_name
0             1                     alcohol misuse
1             2          intimate partner violence
2             3  negative partners (broken person)
3             4                       higher power
4             5       passages (re-entry facility)
5             6                            healing
6             7                  supportive people
7             8                    accountablility
8             9                      coping skills
9            10                              drugs

In [15]:
# merge the two dataframes 
df_aggregate_merge = pd.merge(df_aggregate_names, vars_cld, left_on='variable', right_on='var_name', how='right')
df_aggregate_merge

,theme,variable,vensim_var_no,var_name
0,alcohol use/misuse,alcohol misuse,1,alcohol misuse
1,NaN,NaN,2,intimate partner violence
2,relationship functioning,negative partners (broken person),3,negative partners (broken person)
3,individual protective coping skills,higher power,4,higher power
4,NaN,NaN,5,passages (re-entry facility)
5,NaN,NaN,6,healing
6,NaN,NaN,7,supportive people
7,NaN,NaN,8,accountablility
8,individual protective coping skills,coping skills,9,coping skills
9,NaN,NaN,10,drugs
10,NaN,NaN,11,alcohol exposed pregnancy
11,emotional distress,death,12,death
12,family functioning,family emotional health,13,family emotional health
13,NaN,NaN,14,dire situtations
14,jail/incarceration,jail,15,jail
15,mental health,mental health,16,mental health
16,NaN,NaN,32,intimate partner violence
17,individual protective coping skills,higher power,52,higher power
18,overall resource quality,structure and love,60,structure and love
19,likelihood of child removal from home,family and child loss (legal),61,family and child loss (legal)
20,NaN,NaN,73,drugs
21,NaN,NaN,76,alcohol exposed pregnancy
22,NaN,NaN,78,intimate partner violence
23,alcohol use/misuse,alcohol misuse,84,alcohol misuse

In [18]:
# create a new dictionary the keys in the vensim vars no, the values is the theme column, if the value is nan, the value is variable 
theme_dict = {}
for index, row in df_aggregate_merge.iterrows():
    if pd.isna(row['theme']):
        theme_dict[row['vensim_var_no']] = row['var_name']
    else:
        theme_dict[row['vensim_var_no']] = row['theme']

theme_dict

{'1': 'alcohol use/misuse',
 '2': 'intimate partner violence',
 '3': 'relationship functioning',
 '4': 'individual protective coping skills',
 '5': 'passages (re-entry facility)',
 '6': 'healing',
 '7': 'supportive people',
 '8': 'accountablility',
 '9': 'individual protective coping skills',
 '10': 'drugs',
 '11': 'alcohol exposed pregnancy',
 '12': 'emotional distress',
 '13': 'family functioning',
 '14': 'dire situtations',
 '15': 'jail/incarceration',
 '16': 'mental health',
 '32': 'intimate partner violence',
 '52': 'individual protective coping skills',
 '60': 'overall resource quality',
 '61': 'likelihood of child removal from home',
 '73': 'drugs',
 '76': 'alcohol exposed pregnancy',
 '78': 'intimate partner violence',
 '84': 'alcohol use/misuse'}

In [22]:
df_aggregate_merge

,theme,variable,vensim_var_no,var_name
0,alcohol use/misuse,alcohol misuse,1,alcohol misuse
1,NaN,NaN,2,intimate partner violence
2,relationship functioning,negative partners (broken person),3,negative partners (broken person)
3,individual protective coping skills,higher power,4,higher power
4,NaN,NaN,5,passages (re-entry facility)
5,NaN,NaN,6,healing
6,NaN,NaN,7,supportive people
7,NaN,NaN,8,accountablility
8,individual protective coping skills,coping skills,9,coping skills
9,NaN,NaN,10,drugs
10,NaN,NaN,11,alcohol exposed pregnancy
11,emotional distress,death,12,death
12,family functioning,family emotional health,13,family emotional health
13,NaN,NaN,14,dire situtations
14,jail/incarceration,jail,15,jail
15,mental health,mental health,16,mental health
16,NaN,NaN,32,intimate partner violence
17,individual protective coping skills,higher power,52,higher power
18,overall resource quality,structure and love,60,structure and love
19,likelihood of child removal from home,family and child loss (legal),61,family and child loss (legal)
20,NaN,NaN,73,drugs
21,NaN,NaN,76,alcohol exposed pregnancy
22,NaN,NaN,78,intimate partner violence
23,alcohol use/misuse,alcohol misuse,84,alcohol misuse

In [57]:
# merge the same theme name? 
df_aggregate_merge['theme'].value_counts()

# get all vars no when is "individual protective coping skills"
# df_aggregate_merge[df_aggregate_merge['theme'] == 'individual protective coping skills']

df_aggregate_merge['vensim_var_no'] = df_aggregate_merge['vensim_var_no'].astype(int)
# create a new variable number for the theme 
# max(df_aggregate_merge['vensim_var_no']) + 1  



def get_duplicate_theme_no(df):
    # get all the duplicate theme no 
    df_theme_no = df['theme'].value_counts()
    duplicate_theme_no = df_theme_no[df_theme_no > 1].index.tolist()
    return duplicate_theme_no

test = get_duplicate_theme_no(df_aggregate_merge)
print(test)

['individual protective coping skills', 'alcohol use/misuse']

In [62]:

# create a dictionary where the keys is the orignial var_no and the new var_no is the theme_no
# theme_no_dict = {}
# for index, row in df_aggregate_merge.iterrows():
#     if row['theme'] in test:
#         theme_no_dict[row['vensim_var_no']] = max(df_aggregate_merge['vensim_var_no']) + 1  

theme_no_dict = {}
for i, val in enumerate(test):
    theme_no_dict[val] = max(df_aggregate_merge['vensim_var_no']) + i + 1

theme_no_dict

df_aggregate_merge['theme_no'] = df_aggregate_merge['theme'].map(theme_no_dict)


for i, row in df_aggregate_merge.iterrows():
    if pd.isna(row['theme_no']):
        df_aggregate_merge.at[i, 'theme_no'] = row['vensim_var_no']


df_aggregate_merge['theme_no'] = df_aggregate_merge['theme_no'].astype(int)
# max_num = df_aggregate_merge['vensim_var_no'].max()
# new_dict = {num: max_num + i + 1 for i, num in enumerate(df_aggregate_merge['vensim_var_no'].unique())}
# df_aggregate_merge['theme_no'] = df_aggregate_merge['vensim_var_no'].map(new_dict)
df_aggregate_merge

# df_aggregate_merge

,theme,variable,vensim_var_no,var_name,theme_no
0,alcohol use/misuse,alcohol misuse,1,alcohol misuse,86
1,NaN,NaN,2,intimate partner violence,2
2,relationship functioning,negative partners (broken person),3,negative partners (broken person),3
3,individual protective coping skills,higher power,4,higher power,85
4,NaN,NaN,5,passages (re-entry facility),5
5,NaN,NaN,6,healing,6
6,NaN,NaN,7,supportive people,7
7,NaN,NaN,8,accountablility,8
8,individual protective coping skills,coping skills,9,coping skills,85
9,NaN,NaN,10,drugs,10
10,NaN,NaN,11,alcohol exposed pregnancy,11
11,emotional distress,death,12,death,12
12,family functioning,family emotional health,13,family emotional health,13
13,NaN,NaN,14,dire situtations,14
14,jail/incarceration,jail,15,jail,15
15,mental health,mental health,16,mental health,16
16,NaN,NaN,32,intimate partner violence,32
17,individual protective coping skills,higher power,52,higher power,85
18,overall resource quality,structure and love,60,structure and love,60
19,likelihood of child removal from home,family and child loss (legal),61,family and child loss (legal),61
20,NaN,NaN,73,drugs,73
21,NaN,NaN,76,alcohol exposed pregnancy,76
22,NaN,NaN,78,intimate partner violence,78
23,alcohol use/misuse,alcohol misuse,84,alcohol misuse,86

In [60]:
# check theme_no number dic data type 
df_aggregate_merge['theme_no'].dtypes
# df_aggregate_merge['theme_no'].dtypes

dtype('float64')

In [72]:
theme_no_dict

theme_no_number_dict

{1: 86,
 2: 2,
 3: 3,
 4: 85,
 5: 5,
 6: 6,
 7: 7,
 8: 8,
 9: 85,
 10: 10,
 11: 11,
 12: 12,
 13: 13,
 14: 14,
 15: 15,
 16: 16,
 32: 32,
 52: 85,
 60: 60,
 61: 61,
 73: 73,
 76: 76,
 78: 78,
 84: 86}

In [70]:
new_df.dtypes

from              object
to                object
polarity_type      int64
links              int64
tt               float64
dtype: object

In [92]:
new_df = df.copy()
# change all data in df to int 
new_df = new_df.astype(int)

#swap the from column in df to new number based on theme_no_number_dict
new_df['from'] = new_df['from'].map(theme_no_number_dict)
new_df['to'] = new_df['to'].map(theme_no_number_dict)

# if there is a same row of new_from and new_to add the rows together 
merge_df = new_df.groupby(['from', 'to']).sum().reset_index()

# new_df['theme_no'] = new_df['from'].map(theme_no_number_dict)
# new_df['theme_no'] = new_df['from'].map(theme_no_number_dict)
# new_df['theme_no'] = new_df['theme_no'].fillna(new_df['var_no'])
merge_df

pol_mx = parse_cld.get_adjacency_matrix(merge_df)

In [93]:
pol_mx

to,2,3,5,6,7,8,10,11,12,13,...,15,16,32,60,61,73,76,78,85,86
from,,,,,,,,,,,,,,,,,,,,,
2,0,1,0,0,0,0,1,0,0,0,...,1,1,0,0,0,0,0,0,0,1
3,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,1,0,0,0,0,0,...,0,0,0,1,0,0,0,0,1,0
6,0,0,0,0,1,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
7,0,0,0,1,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
8,0,0,1,1,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,2,0
10,1,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
11,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,0,0
12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
14,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
16,1,0,0,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,2,1
32,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,1,0,0,0,0,0
60,0,0,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
61,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
73,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
76,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
78,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
85,0,1,1,1,0,1,1,0,0,0,...,0,1,0,0,0,0,0,0,1,1
86,1,0,0,0,1,0,1,1,0,1,...,1,1,0,0,1,0,0,0,0,0

In [90]:
pol_mx.columns.astype(str)
pol_mx.index.astype(str)

Index(['nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan',
       'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan',
       'nan'],
      dtype='object', name='from')

In [89]:
pol_mx

to,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
from,,,,,,,,,,,,,,,,,,,,,
NaN,0,1,0,0,0,0,1,0,0,0,...,1,1,0,0,0,0,0,0,0,1
NaN,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
NaN,0,0,0,0,1,0,0,0,0,0,...,0,0,0,1,0,0,0,0,1,0
NaN,0,0,0,0,1,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
NaN,0,0,0,1,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
NaN,0,0,1,1,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,2,0
NaN,1,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
NaN,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,0,0
NaN,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
NaN,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
NaN,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
NaN,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
NaN,1,0,0,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,2,1
NaN,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,1,0,0,0,0,0
NaN,0,0,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
NaN,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
NaN,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
NaN,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
NaN,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
NaN,0,1,1,1,0,1,1,0,0,0,...,0,1,0,0,0,0,0,0,1,1
NaN,1,0,0,0,1,0,1,1,0,1,...,1,1,0,0,1,0,0,0,0,0

In [91]:
# change theme dict keys to int 
theme_dict = {int(k): v for k, v in theme_dict.items()}
theme_dict

{1: 'alcohol use/misuse',
 2: 'intimate partner violence',
 3: 'relationship functioning',
 4: 'individual protective coping skills',
 5: 'passages (re-entry facility)',
 6: 'healing',
 7: 'supportive people',
 8: 'accountablility',
 9: 'individual protective coping skills',
 10: 'drugs',
 11: 'alcohol exposed pregnancy',
 12: 'emotional distress',
 13: 'family functioning',
 14: 'dire situtations',
 15: 'jail/incarceration',
 16: 'mental health',
 32: 'intimate partner violence',
 52: 'individual protective coping skills',
 60: 'overall resource quality',
 61: 'likelihood of child removal from home',
 73: 'drugs',
 76: 'alcohol exposed pregnancy',
 78: 'intimate partner violence',
 84: 'alcohol use/misuse'}

In [94]:
# merge the same theme frame??  

# pol_mx = parse_cld.get_adjacency_matrix(df)

pol_mx.columns = pol_mx.columns.map(theme_dict)

pol_mx.index = pol_mx.index.map(theme_dict)
pol_mx

to,intimate partner violence,relationship functioning,passages (re-entry facility),healing,supportive people,accountablility,drugs,alcohol exposed pregnancy,emotional distress,family functioning,...,jail/incarceration,mental health,intimate partner violence,overall resource quality,likelihood of child removal from home,drugs,alcohol exposed pregnancy,intimate partner violence,NaN,NaN
from,,,,,,,,,,,,,,,,,,,,,
intimate partner violence,0,1,0,0,0,0,1,0,0,0,...,1,1,0,0,0,0,0,0,0,1
relationship functioning,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
passages (re-entry facility),0,0,0,0,1,0,0,0,0,0,...,0,0,0,1,0,0,0,0,1,0
healing,0,0,0,0,1,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
supportive people,0,0,0,1,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
accountablility,0,0,1,1,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,2,0
drugs,1,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
alcohol exposed pregnancy,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,0,0
emotional distress,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
family functioning,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
dire situtations,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
jail/incarceration,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
mental health,1,0,0,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,2,1
intimate partner violence,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,1,0,0,0,0,0
overall resource quality,0,0,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
likelihood of child removal from home,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
drugs,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
alcohol exposed pregnancy,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
intimate partner violence,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
NaN,0,1,1,1,0,1,1,0,0,0,...,0,1,0,0,0,0,0,0,1,1
NaN,1,0,0,0,1,0,1,1,0,1,...,1,1,0,0,1,0,0,0,0,0

In [18]:
# model_name = list(df_rc_themes['Model'])
# # seperate by ";" and "," 
# # model_name = [x.split(";") for x in model_name]
# # model_name
# # get unique model names 
# unique_model_name = list(set(model_name)) 
# print(unique_model_name)

['(many)', 'FC Patients', 'J Model', 'DSS; justice-IPV', 'Justice-drugs; FM model; J model', 'passages', 'FC;justice IPV', 'WAVI;full circle;DSSjustice-drugs; e model;fm model;j model; reentry model', 'FC; Justice-IPV', 'Justice-Drugs ; FC (Provider)', 'Nat Model; reentry model; FM model; E model', 'DSS/Full Circle Provider;E model', 'justice-IPV; FC (Provider)', 'justice-IPV; FM model', 'Justice-drugs', nan, 'FC; justice-IPV', 'DSS', 'DSS; justice-drugs', 'E model', 'WAVI', 'nat model', 'reentry model', 'justice-IPV / e model', 'DSS;E model', 'dss', 'Full circle (Patient)', 'justice - drugs', 'Full Circle (Patient)', 'E Model', 'FC (Provider)', 'justice - ipv', 'DSS; nat model', 'justice-ipv', 'DSS/E model', 'C model', 'FC( Patient)', 'FC; FM model', 'FC', 'all', 'Justice-IPV; FC (Provider)', 'justice-ipv; e model', 'FC (provider)', 'wavi', 'Funding Orgs', 'WAVI;', 'WAVI (combined)', 'WAVI; Justice IPV; Reentry', 'justice-IPV', 'J model', 'E model; FM model', 'Justice  IPV', 'actually receiving/engaging with resources to help address needs', 'FC (patients)', 'Most models', 'Justice IPV', 'J model; reentry model', 'fc (provider)', 'E model?', 'FM Model', 'FC (provider); E model', 'passages;wavi;full circle (patient)', 'e model', 'DSS; FC (Patient); Justice-drugs', 'funding orgs', 'FC;DSS;justice IPV', 'FC (Patient)', 'Justice-drugs; Reentry', 'fudning orgs', 'Full Circle (Provider)', 'WAVI; FC (Patients);DSS;E model; j model', 'Wavi; full circle (patient combined); DSS; Justice-IPV; full circle (provider); FM model; J model; C model', 'j model', 'Passages ', 'Full Circle (Patient); FC Provider', 'FC(Patients)', 'Nat model', 'Justice-Drugs', 'Full Circle (Patient Combined); E model; j model', 'FM Model;  E model', 'Passages', 'FC (Provider); e model', 'justice-drugs;justice-IPV', 'justice-drugs', 'Justice-IPV', 'funding org', 'FM model', 'fc (provider); e model', 'reentry']